version: 2
formats:
 - pdf
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - RPY2_CFFI_MODE=ABI
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: false
