notifications:
  email: false
sudo: required
dist: focal
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
addons:
  apt:
    packages:
    - r-base
    - r-recommended
    - r-cran-lme4
matrix:
 include:
 # see https://www.python.org/downloads/mac-osx/ for valid versions
 - os: osx
   language: r
   cache: packages
   env:
    - MAC_PYTHON_VERSION=3.6.8
    - MAC_PYTHON_OSX_VERSION=10.6
 - os: osx
   language: r
   cache: packages
   env:
    - MAC_PYTHON_VERSION=3.7.9
    - MAC_PYTHON_OSX_VERSION=10.9
 - os: osx
   language: r
   cache: packages
   env:
    - MAC_PYTHON_VERSION=3.8.6
    - MAC_PYTHON_OSX_VERSION=10.9
 - os: linux
   language: python
   python: 3.6
 - os: linux
   language: python
   python: 3.7
 - os: linux
   language: python
   python: 3.8
before_install:
# install other dependencies
- source ./.travis/${TRAVIS_OS_NAME}_setup_python.sh $MAC_PYTHON_VERSION $MAC_PYTHON_OSX_VERSION
install:
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
# install fcswrite
- travis_retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/fcswrite.git --no-deps
# install all other dependencies
# add tensorflow here so its numpy/h5py deps get resolved
- travis_retry pip install --use-feature=2020-resolver -e .[all] tensorflow
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
- coverage run --source=dclab setup.py test
- coverage report -m
- flake8 dclab
- flake8 examples
- flake8 tests
- flake8 scripts
after_success:
- codecov
before_deploy:
- python setup.py sdist
- bash ./.travis/${TRAVIS_OS_NAME}_build_wheel.sh
deploy:
  provider: pypi
  user: "ci_zmdd"
  password:
    secure: "QBTWMuoYKw5SwIBPrB10NPvUiBO36rWrQmu/gz64GAcYKLxucDoY7xnUNIY2zqpXqyrK3iUW/EKNgh9pqd516TyY016MTb2/e1p1Ktp5RF4zDomUZS2TSzxmFn9mvyJOH1mhIGHThP6GWwiKIZeU1kdvTenwEMGFPPStVye5HjzN1RcoK/oBcLL+A5GV/M+g4Edy+KXCLPM/uql1gChIePBuRNCiJ+tDTc1d8EpXLKkIwooKfFiwPBU1F8F+w65NdPIxJuoV5pUmoluJmEiAvJZE2Leu8kRp+bRUj3l4F4PdDVHV7sSlv/Bx8ucTXu+Jz7WAV8jVUxOMAT8TymKimMhQ5KNfTWBJa+1wZ5ljBSsYMerPgpNKd9EYdPX7VgBz1DHyjgBLCrRCDFMa1Ghbdb5TG3/Clf6IZ5fKpJ0qaJlK0fNF15oekt1AYlKRpbHMelP0NgmRdgc+sNsjrftBEhpIP3bs3vF8Ts3UsMGrm6+UEZns3UrDjI+yrYX2PRUOH1Yw1h1ZoIA95Fso7euFFDYYWAxKppGg7YpxWyC8b6z492nQJk+6Y1ViXI8bXEJWG1Sygc8n2I017VAOIPecCHc+kIxFuA/xGG+ee0n2ztjPMb17L5AgH2PnzJxfSkCkfAmnrZJd9Mr7VCFtJpMcErk0EMh8uAXpVX4/5WKk9SM="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
