clone_depth: 256

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  PYPI_PWD:
    secure: 1kFM+4EzTyV0hF7cMxkKQFDuWGhiXfUXCeUGJOTgSbKukTOL9U05/nHi69AtQGpG
  PYPI_USR: ci_zmdd
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"

  # install
  - "appveyor-retry pip install wheel"
  # latest version of fcswrite
  - "appveyor-retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/fcswrite.git --no-deps"
  # the rest
  - "appveyor-retry pip install -e ."
  # Download ffmpeg binary for imageio
  - "appveyor-retry imageio_download_bin --package-dir ffmpeg"
  - "python -m pip freeze"

build: off

test_script:
  - "appveyor-retry pip install coverage"
  - "appveyor-retry pip install codecov"
  - "coverage run --source=dclab ./setup.py test"
  - "coverage report -m"
  # Allow codecov to fail
  - "codecov || exit 0"

after_test:
  - "appveyor-retry pip install twine wheel"
  # If tests are successful, create a whl package for the project.
  - "python setup.py bdist_wheel"
  - "python setup.py sdist"
  # setup PyPI credentials
  - cmd: "echo [pypi] > %USERPROFILE%\\.pypirc"
  - cmd: "echo username: %PYPI_USR% >> %USERPROFILE%\\.pypirc"
  - cmd: "echo password: %PYPI_PWD% >> %USERPROFILE%\\.pypirc"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

on_success:
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] twine upload --skip-existing dist\\*.whl"
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] twine upload --skip-existing dist\\*.tar.gz"
