clone_depth: 256

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  PYPI_PWD:
    secure: 1kFM+4EzTyV0hF7cMxkKQFDuWGhiXfUXCeUGJOTgSbKukTOL9U05/nHi69AtQGpG
  PYPI_USR: ci_zmdd
  RPY2_CFFI_MODE: ABI
  R_HOME: "C:\\Program Files\\R\\R-3.6.3"
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
#    - PYTHON: "C:\\Python37-x64"
#    - PYTHON: "C:\\Python38-x64"

install:
  # actual install
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  # Check that we have the expected version and architecture for Python
  - python --version
  # Install R
#  - choco install -y wget --version 1.20
#  - wget -q https://cran.r-project.org/bin/windows/base/old/3.6.3/R-3.6.3-win.exe
#  - R-3.6.3-win.exe /SILENT /DIR="C:\\Users\\appveyor\\R"
#  - set PATH=%PATH%;"C:\\Users\\appveyor\\R\\bin\\x64"
#  - set PATH=%PATH%;"C:\\Users\\appveyor\\R\\bin\\i386"
#  - set R_HOME="C:\\Users\\appveyor\\R"
#  - set RPY2_CFFI_MODE="ABI"
#  - appveyor R -e "install.packages('lme4', repos='http://cran.r-project.org')"
  - choco install -y r.project --version 3.6.3
  - set PATH=%PATH%;"C:\\Program Files\\R\\R-3.6.3\\bin\x64"
  - set PATH=%PATH%;"C:\\Program Files\\R\\R-3.6.3\\bin"
  - set PATH=%PATH%;"C:\\Program Files\\R\\R-3.6.3"
  - R RHOME
  - set PATH=%PATH%;"C:\\python36-x64\\Scripts"
  # conda
  - conda install -c conda-forge rpy2
  # upgrade pip
  - appveyor-retry python -m pip install --upgrade pip
  # install
  - appveyor-retry pip install wheel
  # latest version of fcswrite
  - appveyor-retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/fcswrite.git --no-deps
  # the rest
  # add tensorflow here so its numpy/h5py deps get resolved
  - appveyor-retry pip install --use-feature=2020-resolver -e .[all] tensorflow
  - python -m pip freeze

build: off

test_script:
  - appveyor-retry pip install pytest
  - appveyor-retry pip install coverage
  - appveyor-retry pip install codecov
  - coverage run --source=dclab ./setup.py test
  - coverage report -m
  # Allow codecov to fail
  - codecov || exit 0

after_test:
  - appveyor-retry pip install twine wheel
  # If tests are successful, create a whl package for the project.
  - python setup.py bdist_wheel
  - python setup.py sdist
  # setup PyPI credentials
  - cmd: "echo [pypi] > %USERPROFILE%\\.pypirc"
  - cmd: "echo username: %PYPI_USR% >> %USERPROFILE%\\.pypirc"
  - cmd: "echo password: %PYPI_PWD% >> %USERPROFILE%\\.pypirc"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

on_success:
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] twine upload --skip-existing dist\\*.whl"
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] twine upload --skip-existing dist\\*.tar.gz"
