name: Checks

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Symlink gfortran (macOS)
      if: runner.os == 'macOS'
      run: |
        # make sure gfortran is available
        ln -s /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
        ln -s /usr/local/gfortran-10 /usr/local/gfortran
        gfortran --version
    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install codecov coverage flake8 pytest
        # install dependencies
        pip install -e .[all]
        # show installed packages
        pip freeze
    - name: Test with pytest
      run: |
        coverage run --source=dclab -m pytest tests
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Submit code coverage
      run: |
        coverage report -m
        codecov
